name: Deploy React app in S3 Bucket

on:
  push:
    branches:
      - main

jobs:
  deploy-on-s3-bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Updated to use the latest version

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Updated to use the latest version
        with:
          node-version: '20' # Explicitly set to Node.js 20

      - name: Install Dependencies
        run: npm install

      - name: Create Build
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Sync & Push to S3 Bucket
        run: aws s3 sync build/ s3://sri-portfolio --delete
